carts/urls.py
"""
Urls de la aplicacion cart
"""
from carts.views import cart_add, cart_detail, cart_remove
from django.urls import path

app_name="carts"
urlpatterns = [
	path('', cart_detail, name="cart_detail"),
	path('agregar/<int:product_id>/', cart_add, name="cart_add"),
	path('borrar/<int:product_id>/', cart_remove, name="cart_remove")
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('tienda/', include('shop.urls', namespace="shop")),    # Declara las urls de la aplicacion shop
    path('cart/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('cupones/', include('coupons.urls', namespace='coupons')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coupons/urls.py
"""urls coupons app."""

# Import django libraries
from django.urls import path

# Import controller/views
from . import views

app_name = 'coupons'
urlpatterns = [
    path('applica/', views.coupon_apply, name='apply'),
]

main/urls.py
"""
Urls de la aplicacion main
"""
from main.views import index, AboutView, ContactUsView  # Nombre de la vista
from django.urls import path

app_name = "main"
urlpatterns = [
    path("", index, name="index"),

    # Acerca de
    path("acerca-de/", AboutView.as_view(), name="about"),
    path("contactanos/", ContactUsView.as_view(), name="contact"),

]

order/urls.py
from django.urls import path
from .views import create_order

app_name = "order"
urlpatterns = [
    path('crear/', create_order, name='create_order'),
]

carts/models.py
from django.db import models

# Create your models here.

carts/forms.py
"""Cart Forms."""

# Import django libraries
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]  # [1 - 10]


class CartAddProductForm(forms.Form):
    # Convierte el input en entero
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int
    )
    # Esto indica si la cantidad agrega alguna cantidad existente en el carrito,
    # False si la cantidad existente ha sido sobrescrita
    override = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

carts/views.py
"""Views/Controller app carts."""

# Import django libraries
from decimal import Decimal

from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.http import require_POST

from shop.models import Product
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from utils.general import Item
from .cart import Cart


# HTTP GET, POST, PUT, DELETE, PATCH

@require_POST  # es un decorador en django que solo permite envios de datos POST.
def cart_add(request, product_id):
    """"""
    cart = Cart(request)
    form = CartAddProductForm(request.POST)
    product = get_object_or_404(Product, id=product_id)  # Obtengo el objeto product
    if form.is_valid():  # True
        data = form.cleaned_data  # Dict {'quantity': 5}
        cart.add(
            qty=data.get("quantity"), product=product,
            edit_qty=data.get("override")
        )  # instancia objecto (producto)
    return redirect('carts:cart_detail')


@require_POST
def cart_remove(request, product_id):
    """"""
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product=product)
    return redirect("carts:cart_detail")


def cart_detail(request):
    cart = Cart(request=request)
    items = []
    # ('1', {"product": <>, "qty": <>, "price": <>})
    for c in cart:
        c[1]['update_quantity_form'] = \
            CartAddProductForm(
                initial={
                    'quantity': c[1].get('quantity'),
                    'override': True
                }
            )
        item = Item(
            quantity=c[1].get("quantity"),
            product=c[1].get("product"),
            price=c[1].get("price"),
            subtotal=round(Decimal(c[1].get("price")) * Decimal(c[1].get("quantity")), 2)
        )
        items.append(item)
    coupon_apply_form = CouponApplyForm()
    return render(request, "carts/detail.html", {'cart': cart, 'items': items, 'coupon_apply_form': coupon_apply_form})

carts/templates/carts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Carrito compras{% endblock %}

{% block content %}
    <h1>Carrito</h1>
    <table class="table" style="margin-top: 5%;">
        <thead>
        <tr>
            <th></th>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Eliminar</th>
            <th>Precio U.</th>
            <th>Sub Total</th>
        </tr>
        </thead>
        <tbody>
        {% for item in items %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="#">
                            {% if product.main_image %}
                                <img src="{{ product.main_image }}" alt="{{ product.name }}" width=200 height=200/>
                            {% else %}
                                <img src="{% static 'images/no_imagen.jpg' %}" alt="No tiene imagen"/>
                            {% endif %}
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>
                        <form action="{% url 'carts:cart_remove' product.id %}" method="post">{% csrf_token %}
                            <input type="submit" value="Eliminar">
                        </form>
                    </td>
                    <td>${{ product.price }}</td>
                    <td>${{ item.subtotal }}</td>
                </tr>
            {% endwith %}
        {% endfor %}

        {% if cart.coupon %}
            <tr class="subtotal">
                <td>SUBTOTAL</td>
                <td colspan="4"></td>
                <td>${{ cart.get_total_subtotal }}</td>
            </tr>
            <tr>
                <td>"{{ cart.coupon.code }}" cupon {{ cart.coupon.discount }}% descuento</td>
                <td colspan="4"></td>
                <td style="color: red">-${{ cart.get_discount|floatformat:2 }}</td>
            </tr>
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td>${{ cart.get_total_price_after_discount|floatformat:2 }}</td>
            </tr>
        {% else %}
            <tr class="total">
                <td>Total</td>
                <td colspan="4"></td>
                <td>${{ cart.get_total_subtotal|floatformat:2 }}</td>
            </tr>
        {% endif %}

        </tbody>
    </table>

    <div class="py-2">
        <h3>Aplicar un cupon:</h3>
        <form action="{% url 'coupons:apply' %}" method="post">{% csrf_token %}
            {{ coupon_apply_form }}
            <input type="submit" value="Aplicar" class="btn btn-warning"/>
        </form>
    </div>

    <section class="text-right">
        <a href="/" class="btn btn-primary">
            Continuar comprando
        </a>
        <a href="{% url 'order:create_order' %}" class="btn btn-secondary">
            Crear Orden
        </a>
    </section>

{% endblock %}