carts/urls.py
"""
Urls de la aplicacion cart
"""
from carts.views import cart_add, cart_detail, cart_remove
from django.urls import path

app_name="carts"
urlpatterns = [
	path('', cart_detail, name="cart_detail"),
	path('agregar/<int:product_id>/', cart_add, name="cart_add"),
	path('borrar/<int:product_id>/', cart_remove, name="cart_remove")
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('tienda/', include('shop.urls', namespace="shop")),    # Declara las urls de la aplicacion shop
    path('cart/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('cupones/', include('coupons.urls', namespace='coupons')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
"""
Urls de la aplicacion main
"""
from main.views import index, AboutView, ContactUsView  # Nombre de la vista
from django.urls import path

app_name = "main"
urlpatterns = [
    path("", index, name="index"),

    # Acerca de
    path("acerca-de/", AboutView.as_view(), name="about"),
    path("contactanos/", ContactUsView.as_view(), name="contact"),

]

order/urls.py
from django.urls import path
from .views import create_order

app_name = "order"
urlpatterns = [
    path('crear/', create_order, name='create_order'),
]

order/models.py
""""""""

# Import standard
from decimal import Decimal

# Import django libraries
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Import custom apps
from coupons.models import Coupon
from shop.models import Product


class Order(models.Model):
    ORDER_STATUS = (
        (1, "Creada"),
        (2, "Procesada"),
        (3, "Enviada"),
        (4, "Pagada"),
        (5, "Completada"),
        (6, "Cancelada"),
    )

    ORDER_PAYMENT_MODE = (
        (1, "Efectivo"),
        (2, "Depostio/Transferencia"),
        (3, "Tarejeta de crédito")
    )

    code = models.CharField(max_length=100, unique=True, verbose_name="Código", help_text="Código único de la orden")
    # Obtiene la fecha actual del servidor (equipo local)
    date_created = models.DateTimeField(verbose_name="Fecha", auto_now=True,
                                        help_text="Fecha de emisión")

    billing_name = models.CharField(max_length=200, verbose_name="Nombres factura",
                                    help_text="Nombres que se ingresan para la factura")
    billing_dni = models.CharField(max_length=20, verbose_name="No. Identificación",
                                   help_text="Numero de idenitifacion")
    billing_email = models.EmailField(verbose_name="Correo")
    billing_phone = models.CharField(max_length=20, null=True, blank=True)

    shipping_name = models.CharField(max_length=200, verbose_name="Nombres para entrega",
                                     help_text="Nombres que reciben el pedido de la orden")
    shipping_address = models.CharField(max_length=200, verbose_name="Dirección de entrega")
    shipping_phone = models.CharField(max_length=20, null=True, blank=True, verbose_name="Telefono para la entrega")

    payment_mode = models.IntegerField(
        default=1,
        choices=ORDER_PAYMENT_MODE, verbose_name="Forma de pago", help_text="modo de pago, Ej tarjeta de credito"
    )
    coupon = models.ForeignKey(
        Coupon,
        related_name='orders',
        null=True,
        blank=True,
        on_delete=models.SET_NULL
    )
    discount = models.IntegerField(
        default=0,
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )

    # Summary
    subtotal = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="SubTotal", default=0.0)
    base12 = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Base 12%", default=0.0)
    base0 = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Base 0%", default=0.0)
    iva = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="IVA", default=0.0)
    fee = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Fee entrega", default=0.0)
    discount_value = models.DecimalField(
        max_digits=9, decimal_places=2,
        verbose_name="Valor del descuento",
        default=0.0
    )
    total = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Total", default=0.0)

    # Orden - procesando, confirmada, entregada, pagada, completada o cancelada
    tracking_status = models.IntegerField(
        choices=ORDER_STATUS, default=1,
        help_text="Estado de seguimiento de la orden", verbose_name="Estado"
    )

    class Meta:
        verbose_name = "Orden"
        verbose_name_plural = "Ordenes"
        db_table = "orden"

    def __str__(self):
        return self.code

    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal(100))


class OrderItem(models.Model):
    # Relacion uno a muchos
    order = models.ForeignKey(
        Order, related_name="items",
        on_delete=models.CASCADE,
        verbose_name="Orden"
    )
    product = models.ForeignKey(Product, related_name="order_items", on_delete=models.CASCADE, verbose_name="Producto")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Precio")
    quantity = models.PositiveIntegerField(default=1, verbose_name="Cantidad")

    def __str__(self):
        return f"[{self.order.code}] Item: {self.product}"

    def get_subtotal(self):
        return round(self.price * self.quantity, 2)

order/forms.py
from django import forms
from django.forms import fields
from .models import Order


class OrderCreateForm(forms.ModelForm):  # ModelForm

    class Meta:
        model = Order
        fields = [
            "billing_name",
            "billing_dni",
            "billing_email",
            "billing_phone",

            "shipping_name",
            "shipping_address",
            "shipping_phone",
            "payment_mode"
        ]

order/views.py
"""Views controller about order."""
from decimal import Decimal

from django.core.mail import send_mail
from django.db import transaction
# Import django libraries
from django.shortcuts import render

# Import custom app
from carts.cart import Cart
from order.forms import OrderCreateForm
from order.models import OrderItem
from utils.general import map_cart_items, generate_unique_code


def create_order(request):
    cart = Cart(request)
    items = map_cart_items(cart)
    order_items = []
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            with transaction.atomic():  # Bloque controlado por transaction
                order = form.save(commit=False)  # Guarda una instancia previa al usar el commit=False de order.
                order.code = generate_unique_code()
                if cart.coupon:
                    order.coupon = cart.coupon
                    order.discount = cart.coupon.discount
                    order.subtotal = cart.get_total_subtotal()  # Suma Subtotales
                    order.base12 = order.subtotal  # Suma de items base12
                    order.iva = cart.get_total_subtotal() * Decimal(0.12)  # calcular impuesto
                    order.discount_value = round(Decimal(cart.get_discount()), 2)
                    order.total = round(cart.get_total_price_after_discount() + Decimal(order.fee))
                else:
                    order.subtotal = cart.get_total_subtotal()
                    order.base12 = order.subtotal
                    order.iva = round(cart.get_total_subtotal() * Decimal(0.12))  # TODO: Dinamico
                    order.total = round(order.subtotal + order.iva + Decimal(order.fee), 2)
                order.save()  # Insert en BD.

                for item in cart:
                    # order_items = [OrderItem1, OrderItem2, ....]
                    order_items.append(
                        OrderItem(
                            order=order,
                            product=item[1].get('product'),  # Instancia de objecto producto
                            price=item[1].get('price'),
                            quantity=item[1].get('quantity')
                        )
                    )
                    # OrderItem.objects.create(
                    # 	order=order,
                    # 	product=item[1].get('product'),	# Instancia de objecto producto
                    # 	price=item[1].get('price'),
                    # 	quantity=item[1].get('quantity')
                    # )
                OrderItem.objects.bulk_create(order_items)
                # Borrar los items asociados a ese carrito
                cart.clear()

                # Metodo de notificacion via correo del cliente
                send_mail(
                    "Commerce| Compra Exitosa",
                    f"Su orden con codigo {order.code} ha generada exitosamente.",
                    "info@commerce.com",
                    [order.billing_email],
                    fail_silently=False,
                )
                return render(request, "order/order_created.html", {'order': order})
    else:
        form = OrderCreateForm()
    return render(
        request, "order/order_form.html",
        {
            'cart': cart, 'form': form, 'items': items
        }
    )

order/templates/order/order_created.html
{% extends 'base.html' %}

{% block content %}
<h2>Gracias</h2>
<p> Su orden ha sido creada exitosamente, su orden de numero {{ order.code }}</p>
{% endblock  %}

order/templates/order/order_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Nueva orden
{% endblock %}


{% block content %}

    <div style="margin: 5rem;">
        <div class="row">
            <div class="col-md-8">
                <form method="post" class="order-form">{% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.billing_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.billing_dni|as_crispy_field }}
                        </div>

                        <div class="form-group col-md-6 mb-0">
                            {{ form.billing_email|as_crispy_field }}
                        </div>

                        <div class="form-group col-md-6 mb-0">
                            {{ form.billing_phone|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.shipping_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.shipping_address|as_crispy_field }}
                        </div>

                        <div class="form-group col-md-6 mb-0">
                            {{ form.shipping_phone|as_crispy_field }}
                        </div>

                        <div class="form-group col-md-6 mb-0">
                            {{ form.payment_mode|as_crispy_field }}
                        </div>
                    </div>


                    <input name="pay" class="btn btn-primary" type="submit" value="Pagar">
                    <a href="{% url 'carts:cart_detail' %}" class="btn btn-secondary">Regresar</a>

                </form>
            </div>
            <div class="col-md-4">
                <h4>Su orden es</h4>
                <ul class="py-3">
                    {% for item in items %}
                        <li>
                            {{ item.quantity }} x {{ item.product.name }}
                            <span>${{ item.subtotal|floatformat:2 }}</span>
                        </li>
                    {% endfor %}
                    {% if cart.coupon %}
                        <li>
                            {{ cart.coupon.code }} descuento del {{ cart.coupon.discount }}%
                            <span class="neg">-${{ cart.get_discount|floatformat:2 }}</span>
                        </li>
                    {% endif %}
                </ul>

                {% if cart.coupon %}
                    <p>Total: ${{ cart.get_total_price_after_discount|floatformat:2 }}</p>
                {% else %}
                    <p>Total: ${{ cart.get_total_subtotal|floatformat:2 }}</p>
                {% endif %}
            </div>
        </div>
    </div>




{% endblock %}
	