carts/urls.py
"""
Urls de la aplicacion cart
"""
from carts.views import cart_add, cart_detail, cart_remove
from django.urls import path

app_name="carts"
urlpatterns = [
	path('', cart_detail, name="cart_detail"),
	path('agregar/<int:product_id>/', cart_add, name="cart_add"),
	path('borrar/<int:product_id>/', cart_remove, name="cart_remove")
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('tienda/', include('shop.urls', namespace="shop")),    # Declara las urls de la aplicacion shop
    path('cart/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('cupones/', include('coupons.urls', namespace='coupons')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
"""
Urls de la aplicacion main
"""
from main.views import index, AboutView, ContactUsView  # Nombre de la vista
from django.urls import path

app_name = "main"
urlpatterns = [
    path("", index, name="index"),

    # Acerca de
    path("acerca-de/", AboutView.as_view(), name="about"),
    path("contactanos/", ContactUsView.as_view(), name="contact"),

]

shop/urls.py
"""
Urls de la aplicacion shop
"""
from shop.views import product_list, ProductDetailView, product_catalogue, product_detail
from django.urls import path

app_name = "shop"

urlpatterns = [
    path("productos/", product_list, name="products"),
    path("productos/<int:pk>/", ProductDetailView.as_view(), name="products_detail"),
    # Catalogue
    path('<slug:category_slug>/', product_catalogue, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', product_detail, name='product_info'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    """
    Categoria de producto
    """
    name = models.CharField(verbose_name="Nombre", help_text="Nombre de la categoría", max_length=200)
    code = models.CharField(verbose_name="Código", help_text="Código representativo de la categoría", max_length=20)
    slug = models.SlugField(
        max_length=200, unique=True, help_text="Texto amigable a mostrar en la url.", null=True
    )
    description = models.TextField(blank=True, null=True, verbose_name="Descripción", help_text="Descripción categoría")
    status = models.BooleanField(default=True, verbose_name="Estado", help_text="Muestra categorias activas")

    def __str__(self):  # toString
        return f"[{self.code}] {self.name}"

    class Meta:
        verbose_name = "Categoría"  # singular
        verbose_name_plural = "Categorías"  # categorías
        db_table = "categoria"  # si no uso el db_table => <nombre_app>_category o shop_category

    def get_absolute_url(self):  # Obtiene la url del modelo, ejemplo: categoria a => /categorias/tecnologia/
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    """
    Clase producto
    """
    sku = models.CharField(max_length=50, unique=True, verbose_name="SKU", help_text="Codigo control inventario")
    name = models.CharField(max_length=150, verbose_name="Nombre", help_text="Nombre producto")
    slug = models.SlugField(
        max_length=200, db_index=True, null=True, help_text="Texto amigable a mostrar en la url."
    )
    price = models.DecimalField(verbose_name="Precio venta", decimal_places=2, max_digits=8,
                                help_text="Precio de venta en USD.")
    category = models.ForeignKey(
        Category, verbose_name="Categoría",
        help_text="Categoría del producto",
        on_delete=models.SET_NULL, null=True, blank=True
    )
    stock = models.BooleanField(default=True, verbose_name="Disponibilidad", help_text="Existencia del producto")
    description = models.TextField(blank=True, default='', verbose_name="Descripción",
                                   help_text="Descripción del producto")

    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
        db_table = "producto"

    def __str__(self):
        return f"{self.name}"

    @property  # Decorador
    def main_image(self):
        if self.images.first():
            return self.images.first().photo.url  # /images/laptop.jpg
        else:
            return None

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])


class ProductImage(models.Model):
    """
    """
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE,
        verbose_name="Producto", related_name="images"
    )
    photo = models.ImageField(upload_to="product-images")  # Directorio donde se almacena las imagenes
    thumbnail = models.ImageField(upload_to="product-thumbnails", null=True,
                                  blank=True)  # Es opcional en el administrador.

    class Meta:
        verbose_name = "Imagen producto"
        verbose_name_plural = "Imagenes producto"
        db_table = "producto_image"

    def __str__(self):
        return f"Foto de {self.product}"

shop/views.py
"""Views/controller about shop."""

# Import django libraries
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, ListView

# Import custom apps
from carts.forms import CartAddProductForm
from .models import Product, Category  # Importando el modelo Product


# Vista basada en funcion
def product_list(request):
    print("Controlador de listado de productos")
    # API ORM DJANGO

    # SELECT * from product;
    products = Product.objects.all()  # Traer todos los registros de productos
    # print("cantidad: ", products.count())	# Recomendado
    # print(len(products))	# No se recomienda
    # Trae todos los registros de productos // select * from producto where stock = False;
    verified = Product.objects.filter(
        stock=False).exists()
    if verified:  # Boolean -> True o False
        print("Cuantos productos NO tengo disponibles: ",
              Product.objects.filter(stock=False).count())
    else:
        print("mis productos estan disponibles")
    context = {
        "products": products,
        "categories": Category.objects.filter(status=True)
    }
    return render(request, "shop/product_list.html", context)  # HTTPRESPONSE


# Vista basada en clase
class ProductDetailView(DetailView):  # CreateView, UpdateView, DeleteView, ListView
    """
    Vista o controlador que muestra la información de un objeto producto.
    """
    model = Product
    template_name = "shop/product_detail.html"
    context_object_name = "product"  # Atributo que indica el nombre de la variable que representa el objeto

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_product_form = CartAddProductForm()

        context["cart_product_form"] = cart_product_form
        context["title"] = "Detalle del producto en la vista de clase"
        return context


class ProductsListView(ListView):
    """

    """
    model = Product
    template_name = "shop/product_list.html"
    queryset = Product.objects.all()
    context_object_name = "products"


def product_catalogue(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(
        request,
        "shop/product_list.html", {
            'category': category,
            'categories': categories,
            'products': products
        }
    )


def product_detail(request, id, slug):
    product = get_object_or_404(
        Product, id=id, slug=slug, stock=True
    )
    cart_product_form = CartAddProductForm()
    return render(
        request, "shop/product_detail.html",
        {
            'product': product,
            'cart_product_form': cart_product_form
        }
    )

shop/templates/shop/product_detail.html
{% extends "base.html" %} 
{% load static %}

{% block title %}Detalle producto {{producto.name}} {% endblock %} 


{% block content %}

	<div class="container">
		<div class="pt-5">
			{# Validar si existe foto presentarla o colocar un placeholder #}
			{% if product.main_image %}
				<img src="{{ product.main_image }}" alt="{{ product.name }}" width=200 height=200 />
			{% else %}
				<img src="{% static 'images/no_imagen.jpg' %}" alt="No tiene imagen" />	
			{% endif %}
			<h1>{{ product.name }}</h1>
			<h2>
				<a href="#">
					{{ product.category }}
				</a>
			</h2>
			<p class="price">${{ product.price }}</p>

			{# formulario de cantidad para agregar al carrito #}
			<form action="{% url 'carts:cart_add' product.id %}" method="post">{% csrf_token %}
				{{ cart_product_form }} 
				<br>
				{{ title }}
				<input type="submit" value="Agregar al carrito" />
			</form>

			{{ product.description|linebreaks }}	{# Template filter de django que permite parrafos salto de lineas #}
		</div>
	</div>	
{% endblock %}

shop/templates/shop/product_list.html
{% extends 'base.html' %}
{% block title %} Catalogo Productos {% endblock %}

{% block content %}
<div class="row">

    <div class="col-lg-3">

        <h1 class="my-4">Tienda</h1>
            <div class="list-group">
                {% for category in categories %} 
                    <a href="{{ category.get_absolute_url }}" class="list-group-item">
                        {{ category.name }}
                    </a> 
                {% endfor %}
            </div>
    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="carousel-item active">
                    <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                </div>
                <div class="carousel-item">
                    <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>

        <div class="row">
            {% for product in products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="{% url 'shop:products_detail' product.pk %}">

                            {% if product.images.exists %}
                                <img class="card-img-top" 
                                    src="{{ product.main_image }}" 
                                    alt="{{ product.name }}" />
                            {% else %}
                                <img class="card-img-top" 
                                    src="http://placehold.it/700x400" alt="{{ product.name }}" />
                            {% endif %}

                        </a>

                    <div class="card-body">
                        <h4 class="card-title">
                            {# TODO: implement in model #}
                            <a href="#">
                                {{ product.name }}
                            </a>
                        </h4>
                        <h5>${{product.price}}</h5>
                        <p class="card-text">{{product.description}}</p>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- /.row -->

    </div>
    <!-- /.col-lg-9 -->

</div>
<!-- /.row -->
{% endblock %}