config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.urls.conf import include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('tienda/', include('shop.urls', namespace="shop")),    # Declara las urls de la aplicacion shop
    path('cart/', include('carts.urls', namespace="carts")),
    path('order/', include('order.urls', namespace="order")),
    path('cupones/', include('coupons.urls', namespace='coupons')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
"""
Urls de la aplicacion main
"""
from main.views import index, AboutView, ContactUsView  # Nombre de la vista
from django.urls import path

app_name = "main"
urlpatterns = [
    path("", index, name="index"),

    # Acerca de
    path("acerca-de/", AboutView.as_view(), name="about"),
    path("contactanos/", ContactUsView.as_view(), name="contact"),

]

config/templates/base.html
<!-- Carga ruta de estaticos -->
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Commerce | {% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" /> {% block extra-css %}{% endblock %}

    <!-- Custom styles project -->
    <link href="{% static 'css/styless.css' %}" rel="stylesheet" />

</head>

<body>

    <!-- Navigation Header -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <!-- Logo -->
            <a class="navbar-brand" href="{% url 'main:index' %}">Commerce</a>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:about' %}">Acerca de</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:contact' %}">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

        {% block content %} {% endblock %}

    </div>
    <!-- /.container -->


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    {% block extra-js %}{% endblock %}

</body>

</html>